spring:
  profiles:
    active: dev
---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
    
eureka:
  instance:
    hostname: localhost1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: springcloud-config-eureka
    
eureka:
  instance:
    hostname: localhost1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/   